### ISSUE TITLE
'Content-Type was not one of "multipart/form-data" or "application/x-www-form-urlencoded".' when making POST request

### ISSUE THREAD

**Issue by Melvillian** [xstevenyung/astro-htmx#6]
I was following this short tutorial about using Astro partials and POSTing form data using HTMX + Astro:

https://blog.trevfox.dev/posts/htmx-and-astro-partials

and found an error where, when I have a backend POST request handler like so:

```astro
---
export const partial = true;
export const prerender = false;

if (Astro.request.method !== "POST") {
  return new Response("Method not allowed.", { status: 405 });
}

const formData = await Astro.request.formData();
const input1 = formData.get("post-input-1")?.toString();
const input2 = formData.get("post-input-2")?.toString();
---

<li class="my-0 text-sky-600">{input1 + input2}</li>
```

and a frontend HTMX snippet that looks like so:

```htmx
<body>
    <h1>Astro</h1>
    <div hx-get="/api/first" hx-trigger="load" hx-swap="outerHTML"></div>
    <div class="mt-4">
      <input
        name="post-input-1"
        class="post-input rounded border border-black bg-slate-200 px-2"
        id="post-input-1"
        type="text"
      />
      <input
        name="post-input-2"
        class="post-input rounded border border-black bg-slate-200 px-2"
        id="post-input-2"
        type="text"
      />
      <button
        class="rounded bg-slate-200 px-2"
        hx-post="/api/postit"
        hx-target="next #post-output"
        hx-swap="beforeend"
        hx-include=".post-input"
        >Post It!
      </button>
      <ol id="post-output"></ol>
    </div>
  </body>
```
  
I get the following error:

```
  TypeError: Content-Type was not one of "multipart/form-data" or "application/x-www-form-urlencoded".
    at node:internal/deps/undici/undici:4251:19
    at successSteps (node:internal/deps/undici/undici:4274:27)
    at consumeBody (node:internal/deps/undici/undici:4280:9)
    at _Request.formData (node:internal/deps/undici/undici:4228:18)
    at /Users/melvillian/code/htmx/htmx-and-astro-partials-howto/src/pages/api/postit.astro:9:38
    at postit (/Users/melvillian/code/htmx/htmx-and-astro-partials-howto/node_modules/astro/dist/runtime/server/astro-component.js:16:12)
    at callComponentAsTemplateResultOrResponse (file:///Users/melvillian/code/htmx/htmx-and-astro-partials-howto/node_modules/astro/dist/runtime/server/render/astro/render.js:90:31)
    at renderToAsyncIterable (file:///Users/melvillian/code/htmx/htmx-and-astro-partials-howto/node_modules/astro/dist/runtime/server/render/astro/render.js:132:32)
    at renderPage (file:///Users/melvillian/code/htmx/htmx-and-astro-partials-howto/node_modules/astro/dist/runtime/server/render/page.js:31:30)
    at lastNext (file:///Users/melvillian/code/htmx/htmx-and-astro-partials-howto/node_modules/astro/dist/core/render-context.js:141:31)
```

I know this isn't a problem with your `astro-htmx` repo. But it does have to do with a combination of HTMX POST requests on the frontend and Astro backend handlers, so I'm making an issue here so the Great Search Engine In The Sky will slurp it up and help future folks who face this issue.

**Comment by Melvillian** [comment]
Turns out the solution is to add the following to your `astro.config.mjs` file:

```js
// @ts-check
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  output: 'server',
});
```

either `server` or `hybrid` will work, as long as it's not the default `static` config value. You can read more about the meaning of these config options [here](https://docs.astro.build/en/reference/configuration-reference/#output)
